name: PassPar2-app App with Gradle  # Nom du workflow

on:
  push:
    branches: [ "*" ]  # Déclenche le workflow sur un push sur n'importe quelle branche
  pull_request:
    branches: [ "*" ]  # Déclenche le workflow lors d'une pull request sur n'importe quelle branche

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu comme environnement de build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Clone le code source du dépôt dans l'environnement GitHub Actions

    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Installe Java
      with:
        java-version: '17'  # Utilise Java 17
        distribution: 'corretto'  # Choisit la distribution Corretto (Amazon)

    - name: Ensure Gradle Wrapper is executable
      run: chmod +x gradlew  # Rend le script Gradle Wrapper exécutable

    - name: Cache Gradle dependencies
      uses: actions/cache@v3  # Active un cache pour accélérer les builds en évitant de retélécharger les dépendances
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4  # Configure Gradle et initialise l'environnement

    - name: Build Android app with Gradle
      run: ./gradlew assembleDebug --info --stacktrace  # Compile l'application Android en mode Debug
